CREATE TABLE fred_teste (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100),
    PRIMARY KEY (id)
);

INSERT INTO clientes (nome) VALUES ('Nico Robbin');
INSERT INTO clientes (nome) VALUES ('Zoro');
INSERT INTO clientes (nome) VALUES ('Sanji');
INSERT INTO clientes (nome) VALUES ('Luffy');

COMMIT;